import Facility from '../models/Facility.js';
import StorageUnit from '../models/StorageUnit.js';
import Sensor from '../models/Sensor.js';
import Alert from '../models/Alert.js';
import WorkOrder from '../models/WorkOrder.js';
import ComplianceRecord from '../models/ComplianceRecord.js';
import Telemetry from '../models/Telemetry.js';
import { logAuditEvent } from '../services/auditService.js';

export const getExecutiveDashboardMetrics = async (req, res, next) => {
  try {
    const query = {};
    if (req.user.role !== 'Super Admin') {
      query._id = { $in: req.user.assignedFacilities };
    }

    const facilityQuery = query._id ? { facility: query._id } : {};

    const [
      facilities,
      storageUnitsCount,
      sensorStats,
      activeAlerts,
      unackCriticalAlerts,
      workOrderStats,
      complianceRecords,
      recentAlerts,
      recentWorkOrders
    ] = await Promise.all([
      Facility.find(query).select('name code status totalCapacityKg currentStorageKg lastTelemetryTimestamp'),
      StorageUnit.countDocuments(facilityQuery),
      Sensor.aggregate([
        { $match: facilityQuery },
        { $group: {
          _id: null,
          total: { $sum: 1 },
          online: { $sum: { $cond: [{ $eq: ['$connectionStatus', 'Online'] }, 1, 0] } },
          offline: { $sum: { $cond: [{ $eq: ['$connectionStatus', 'Offline'] }, 1, 0] } },
          calOverdue: { $sum: { $cond: [{ $eq: ['$status', 'Calibration Overdue'] }, 1, 0] } }
        }}
      ]),
      Alert.countDocuments({
        ...facilityQuery,
        status: { $in: ['New', 'Acknowledged', 'Assigned', 'Investigating'] }
      }),
      Alert.countDocuments({
        ...facilityQuery,
        severity: 'Critical',
        status: 'New'
      }),
      WorkOrder.aggregate([
        { $match: facilityQuery },
        { $group: {
          _id: null,
          total: { $sum: 1 },
          overdue: { $sum: { $cond: [{ $and: [{ $lt: ['$dueDate', new Date()] }, { $ne: ['$status', 'Completed'] }, { $ne: ['$status', 'Cancelled'] }] }, 1, 0] } },
          upcoming: { $sum: { $cond: [{ $and: [{ $gte: ['$dueDate', new Date()] }, { $lte: ['$dueDate', new Date(Date.now() + 7*24*60*60*1000)] }, { $ne: ['$status', 'Completed'] }] }, 1, 0] } }
        }}
      ]),
      ComplianceRecord.aggregate([
        { $match: facilityQuery },
        { $group: {
          _id: null,
          total: { $sum: 1 },
          compliant: { $sum: { $cond: [{ $eq: ['$status', 'Compliant'] }, 1, 0] } },
          avgScore: { $avg: '$overallScorePercent' }
        }}
      ]),
      Alert.find(facilityQuery)
        .populate('facility', 'name code')
        .populate('sensor', 'sensorId type')
        .sort({ createdAt: -1 })
        .limit(6),
      WorkOrder.find(facilityQuery)
        .populate('facility', 'name code')
        .populate('assignedTo', 'name')
        .sort({ dueDate: 1 })
        .limit(6)
    ]);

    const sStats = sensorStats[0] || { total: 0, online: 0, offline: 0, calOverdue: 0 };
    const woStats = workOrderStats[0] || { total: 0, overdue: 0, upcoming: 0 };
    const cStats = complianceRecords[0] || { total: 0, compliant: 0, avgScore: 100 };

    const statusCounts = {
      Normal: facilities.filter(f => f.status === 'Normal').length,
      Warning: facilities.filter(f => f.status === 'Warning').length,
      Critical: facilities.filter(f => f.status === 'Critical').length,
      Maintenance: facilities.filter(f => f.status === 'Maintenance').length,
      Offline: facilities.filter(f => f.status === 'Offline').length
    };

    const totalStorageCapacity = facilities.reduce((sum, f) => sum + (f.totalCapacityKg || 0), 0);
    const currentStoredKg = facilities.reduce((sum, f) => sum + (f.currentStorageKg || 0), 0);

    res.status(200).json({
      success: true,
      data: {
        facilitiesCount: facilities.length,
        facilityStatusCounts: statusCounts,
        facilities,
        storageUnitsCount,
        storageUtilizationPercent: totalStorageCapacity > 0 ? Math.round((currentStoredKg / totalStorageCapacity) * 100) : 0,
        totalStorageCapacity,
        currentStoredKg,
        sensorStats: sStats,
        activeAlerts,
        unackCriticalAlerts,
        workOrderStats: woStats,
        complianceRate: Math.round(cStats.avgScore || 100),
        recentAlerts,
        recentWorkOrders,
        simulationNotice: 'SYNTHETIC TELEMETRY: Data is generated by the HydroSentinel simulator for demonstration and validation.'
      }
    });
  } catch (error) {
    next(error);
  }
};

export const getAlertAnalytics = async (req, res, next) => {
  try {
    const query = {};
    if (req.user.role !== 'Super Admin') {
      query.facility = { $in: req.user.assignedFacilities };
    }

    // Calculate descriptive MTTA and MTTR
    const resolvedAlerts = await Alert.find({
      ...query,
      status: { $in: ['Resolved', 'Closed'] },
      acknowledgedAt: { $exists: true },
      resolvedAt: { $exists: true }
    }).select('createdAt acknowledgedAt resolvedAt severity category facility').lean();

    let totalAckTimeMinutes = 0;
    let totalResTimeMinutes = 0;

    resolvedAlerts.forEach(a => {
      const ackDiff = (new Date(a.acknowledgedAt) - new Date(a.createdAt)) / (1000 * 60);
      const resDiff = (new Date(a.resolvedAt) - new Date(a.createdAt)) / (1000 * 60);
      totalAckTimeMinutes += Math.max(0, ackDiff);
      totalResTimeMinutes += Math.max(0, resDiff);
    });

    const mtta = resolvedAlerts.length > 0 ? Math.round(totalAckTimeMinutes / resolvedAlerts.length) : 8; // minutes
    const mttr = resolvedAlerts.length > 0 ? Math.round(totalResTimeMinutes / resolvedAlerts.length) : 42; // minutes

    // Alert trend by day (last 7 days)
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const alertsByDay = await Alert.aggregate([
      { $match: { ...query, createdAt: { $gte: sevenDaysAgo } } },
      { $group: {
        _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } },
        total: { $sum: 1 },
        critical: { $sum: { $cond: [{ $eq: ['$severity', 'Critical'] }, 1, 0] } },
        warning: { $sum: { $cond: [{ $eq: ['$severity', 'Warning'] }, 1, 0] } }
      }},
      { $sort: { _id: 1 } }
    ]);

    res.status(200).json({
      success: true,
      data: {
        mttaMinutes: mtta,
        mttrMinutes: mttr,
        mttaDescription: 'Mean Time to Acknowledge (synthetic sample duration from alarm trigger to user acknowledgement)',
        mttrDescription: 'Mean Time to Resolve (synthetic sample duration from alarm trigger to verified resolution)',
        sampleSize: resolvedAlerts.length,
        trendLast7Days: alertsByDay
      }
    });
  } catch (error) {
    next(error);
  }
};

export const exportDataCSV = async (req, res, next) => {
  try {
    const { module, facilityId } = req.query;
    let csv = '';
    let filename = `hydrosentinel_export_${module || 'data'}_${Date.now()}.csv`;

    const facilityQuery = facilityId ? { facility: facilityId } : {};

    if (module === 'alerts') {
      const alerts = await Alert.find(facilityQuery)
        .populate('facility', 'name code')
        .populate('sensor', 'sensorId type')
        .sort({ createdAt: -1 })
        .limit(500);

      csv = 'AlertID,FacilityCode,FacilityName,SensorID,Category,Severity,Status,TriggeredValue,Threshold,Unit,CreatedAt\n';
      alerts.forEach(a => {
        csv += `"${a._id}","${a.facility?.code || ''}","${a.facility?.name || ''}","${a.sensor?.sensorId || ''}","${a.category}","${a.severity}","${a.status}",${a.triggeredValue || ''},${a.thresholdValue || ''},"${a.unit || ''}","${a.createdAt.toISOString()}"\n`;
      });
    } else if (module === 'work-orders') {
      const orders = await WorkOrder.find(facilityQuery)
        .populate('facility', 'code name')
        .populate('assignedTo', 'name email')
        .sort({ dueDate: 1 });

      csv = 'WorkOrderNo,Title,Category,Priority,Status,FacilityCode,AssignedTechnician,DueDate,CompletedDate\n';
      orders.forEach(w => {
        csv += `"${w.workOrderNumber}","${w.title.replace(/"/g, '""')}","${w.category}","${w.priority}","${w.status}","${w.facility?.code || ''}","${w.assignedTo?.name || 'Unassigned'}","${w.dueDate?.toISOString() || ''}","${w.completedDate?.toISOString() || ''}"\n`;
      });
    } else if (module === 'compliance') {
      const records = await ComplianceRecord.find(facilityQuery)
        .populate('facility', 'code name')
        .populate('checklist', 'title category code')
        .populate('completedBy', 'name');

      csv = 'RecordID,FacilityCode,ChecklistCode,ChecklistTitle,Category,ScorePercent,Status,InspectionDate,InspectedBy\n';
      records.forEach(r => {
        csv += `"${r._id}","${r.facility?.code || ''}","${r.checklist?.code || ''}","${r.checklist?.title || ''}","${r.checklist?.category || ''}",${r.overallScorePercent},"${r.status}","${r.inspectionDate.toISOString()}","${r.completedBy?.name || ''}"\n`;
      });
    } else {
      // Default to sensor inventory
      const sensors = await Sensor.find(facilityQuery)
        .populate('facility', 'code name')
        .populate('storageUnit', 'unitId name');

      csv = 'SensorID,Name,Type,FacilityCode,StorageUnit,Unit,Status,ConnectionStatus,LastReading,LastCalibration,NextDue\n';
      sensors.forEach(s => {
        csv += `"${s.sensorId}","${s.name}","${s.type}","${s.facility?.code || ''}","${s.storageUnit?.unitId || ''}","${s.unit}","${s.status}","${s.connectionStatus}",${s.lastReading?.value !== undefined ? s.lastReading.value : ''},"${s.lastCalibrationDate?.toISOString() || ''}","${s.nextCalibrationDue?.toISOString() || ''}"\n`;
      });
    }

    await logAuditEvent({
      actor: req.user,
      action: 'DATA_EXPORT_CSV',
      targetEntity: 'Export',
      details: { module, facilityId }
    });

    res.header('Content-Type', 'text/csv');
    res.attachment(filename);
    res.status(200).send(csv);
  } catch (error) {
    next(error);
  }
};
